#!/usr/bin/env bash

if [ ! -d ~/.tmux/plugins/tpm ]; then
  git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
fi

if [ ! -d ~/.tmuxifier ]; then
  git clone https://github.com/jimeh/tmuxifier.git ~/.tmuxifier
fi


# docker post install
sudo usermod -aG docker $USER
newgrp docker
sudo systemctl enable docker
sudo systemctl start docker

