modmap:
  - name: it's for key to key remap
    remap:
      CapsLock: Ctrl_L
keymap:
  - name: Global
    remap:
      C-Shift-h: left
      C-Shift-j: down
      C-Shift-k: up
      C-Shift-l: right
